services:
    vote.repository:
        class: AppBundle\Repository\VoteRepository
        factory: [ "@doctrine", 'getRepository' ]
        arguments:
            - AppBundle\Entity\Vote

    vote_result.repository:
        class: AppBundle\Repository\VoteResultRepository
        factory: [ "@doctrine", 'getRepository' ]
        arguments:
            - AppBundle\Entity\VoteResult
